### ISSUE TITLE
Compile thew project for MKSSBASE1.3

### ISSUE THREAD

**Issue by 00alkskodi00** [gnea/grbl-LPC#14]
Hi i need to compile this project for the MKSSBASE1.3 i have a problem whit this manual: https://github.com/gnea/grbl-LPC/wiki

i can compile only original smoothieware firmware, but i can not compile this firmware for MKSSBASE1.3 ...

have everyone tutorial?

thanks, sorry for my enslish

this is a very cool project!!!!

here is my maschine whit arduino, but i have now MKSSBASE:
https://www.youtube.com/watch?v=YtH1sCQrMhk

**Comment by cprezzi** [comment]
Please use my fork, which has precompiled releases for multiple boards (also MKS SBASE).
See https://github.com/cprezzi/grbl-LPC/releases
