### ISSUE TITLE
Windows Comiple Issue

### ISSUE THREAD

**Issue by PermatechCA** [gnea/grbl-LPC#15]
Good morning I hope someone might be able to point me in the right direction.

I am using a windows 10 system. 
I have installed the GNU make for windows and the GNU ARM toolchain
I have git cloned this repository, then git submodule init and the update (received checksums)
I have been to the environment variables and added the toolchain and make bins to the local user Path
I have tested the version of the toolchain and make and got positive response.

But when I "make" this is my response:
 
C:/Program Files/Git/usr/bin/sh.exe -c "mkdir -p \"build\""
/usr/bin/sh: C:/Program: No such file or directory
make: *** [build/src/coolant_control.o] Error 127

Any help would be much appreciated

**Comment by mayhem2408** [comment]
@elmo-poog Try moving everything into a folder without a space in the name. I had the same problem. It worked for me.

**Comment by PermatechCA** [comment]
Thank you very much. Problem solved!
