### ISSUE TITLE
please help, compileeeeee

### ISSUE THREAD

**Issue by 00alkskodi00** [gnea/grbl-LPC#16]
have everyone tutorial how can i make this:

Build notes:
* You should use virtual machines, if you use multiple toolchains on the same PC.
* Install make if not already there (for Windows see http://gnuwin32.sourceforge.net/packages/make.htm)
* Install the ARM embeded toolchain (see https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads)
* Include ```make``` and the ```arm-none-eabi-*``` tools in your path.
* Run ```git submodule init ``` and ```git submodule update``` before building.
* ```make``` produces 2 files:
  * ```build/firmware.bin```: this is compatible with the sdcard bootloader.
  * ```build/grbl.hex```: this is not compatible with the sdcard bootloader. It loads using Flash Magic 
    and is primarilly for developers who don't want to keep swapping sdcards. If you flash this,
    then you'll have to reflash the bootloader if you want to go back.

i am not a programator :(

**Comment by cprezzi** [comment]
Closed because "double entry"
