### ISSUE TITLE
MKS Sgen L

### ISSUE THREAD

**Issue by Alf3181** [gnea/grbl-LPC#22]
Hello,
i test GRBL with Arduino Uno for CO² Laser.
But the Controller is to slow.

So i buy an MKS SGen L
but with Marlin 2.0 and Smoothieware didnt work.

Here is GRBL LPC availe for MKS SBase thats work with LPC1758 prozessor.
Is it posible to pinmapping for Sgen L and dissable the stepper current over software.
Or have some one a firmeware for this board.

current run plan and pin out are here:
https://github.com/makerbase-mks/SGEN_L

Sorry for my bad english :)

**Comment by cprezzi** [comment]
Nope, it's not possible to get grbl_LPC to work on the SGen L, because pin mapping is not compatible.
