### ISSUE TITLE
Compiling in Platform IO

### ISSUE THREAD

**Issue by wazaman** [gnea/grbl-LPC#24]
Hi !

Could you help me please, I m wondering if it is possible to compile your new firmware grbl lpc with Platform IO ?

I have a mks robin nano V3 and I saw it can handle a laser so I d like to try... Other question : if I can t compile in PIO, how to do with arduino 1.8.13 ? As I could see, proc is a STM32F407VGT6 known as STM32 ARM Cortex-M4F in marlin nighly.

I hope been clear...

Thank you a lot

**Comment by cprezzi** [comment]
I don't know if it could be compiled with Platform IO or Arduino, but it anyways will not work for an mks robin nano board, because this firmware only works with LPC1769 Chip.
